modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/EnvyWare/EnvySpecs"

[[mods]]
modId="envyspecs"
version="1.2.0"
displayName="EnvySpecs"
displayURL="https://github.com/EnvyWare"
credits="Envyful"
authors="https://github.com/EnvyWare"
description='''
EnvySpecs
'''

[[dependencies.envyspecs]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.envyspecs]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"